# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  perl: circleci/perl@1.0.0

workflows:
  main:
    jobs:
      - perl/build:
          codecov: false
          save-to-artifacts: false
          save-to-workspace: false
      - perl/test-linux:
          matrix:
            parameters:
              perl-version:
                - '5.22'
                - '5.24'
                - '5.26'
                - '5.28'
                - '5.30'
                - '5.32'
          requires:
            - perl/build