version: 2.1
orbs:
  perl: circleci/perl@1.0.0
workflows:
  main:
    jobs:
      - perl/build:
          codecov: true
          save-to-artifacts: true
          save-to-workspace: true
      - perl/test-linux:
          matrix:
            parameters:
              perl-version:
                - '5.22'
                - '5.24'
                - '5.26'
                - '5.28'
                - '5.30'
                - '5.32'                
          requires:
            - perl/build
