---
version: 2.1
jobs:

  buildtest:
    parameters:
      perlv:
        description: "The Perl version we want to do the build and test with"
        # default: "5.32"
        type: string
    docker:
      # - image: perldocker/perl-tester:<< pipeline.parameters.perlv >>
      - image: perldocker/perl-tester:<< parameters.perlv >>
    steps:
      - checkout
      - run:
          command: perl -V; pwd;
          # working_directory: Hello
      - run:
          command: cpanm Dist::Zilla::Plugin::CheckChangeLog
      - run:
          # description: Install Hello dependencies
          command: pwd; dzil listdeps | xargs cpanm;
          # working_directory: Hello
      - run:
          description: Test Hello
          command: prove -l t/*.t
          # working_directory: Hello

workflows:
  build:
    jobs:
      - buildtest:
          matrix:
            parameters:
              perlv:
                - '5.24'
                - '5.26'
                - '5.28'
                - '5.30'
                - '5.32'
