=pod

=head1 Name

Vote::Count::Helper

=head1 Description

Helpers for Vote::Count.

=head1 Inventory

=over 1

=item L<FullCascadeCharge|http://metacpan.org/pod/Vote::Count::Helper::FullCascadeCharge>

=item L<NthApproval|http://metacpan.org/pod/Vote::Count::Helper::NthApproval>

=item L<Table|http://metacpan.org/pod/Vote::Count::Helper::Table>

=back

=cut
#FOOTER

=pod

BUG TRACKER

L<https://github.com/brainbuz/Vote-Count/issues>

AUTHOR

John Karr (BRAINBUZ) brainbuz@cpan.org

CONTRIBUTORS

Copyright 2019-2020 by John Karr (BRAINBUZ) brainbuz@cpan.org.

LICENSE

This module is released under the GNU Public License Version 3. See license file for details. For more information on this license visit L<http://fsf.org>.

=cut

